# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 06:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 5, 27, 6, 29, 57, 341846, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
