# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gapp', '0002_auto_20160527_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gapp.Country'),
        ),
    ]
